### ISSUE TITLE
veritabanı

### ISSUE THREAD

**Issue by isasarioglann** [berkanumutlu/Odev-Takip-Otomasyonu#2]
projeniz çok iyi görünüyor elinize sağlık ama veritabanı bağlama kısmı eksik kalmış. Rica etsem veritabanı kısmını atabilir misiniz? cevabınızı bekliyorum

**Comment by berkanumutlu** [comment]
Merhaba @isasarioglann,

Veri tabanı yapısına https://github.com/berkanumutlu/Odev-Takip-Otomasyonu/issues/1#issuecomment-2085472142 adresinden ulaşabilirsin.
